version: "3.7"

services:
  app:
    build:
      context: ./patient_service
    ports:
      - 8001:8000
    container_name: painkiller-python-app
    volumes:
      - ./patient_service/app:/app
    command: 
        # sh -c "python listener.py"
        sh -c "uvicorn main:app --host 0.0.0.0 --reload --port 8000"
    depends_on:
      - postgresql-measurement-svc2
    env_file:
      - ./patient_service/.env
    networks:
        - rabbitmq_go_net

  measurement_service:
    build:
      context: ./measurement_service
    ports:
      - 8002:8000
    container_name: painkiller-measurement-python-app
    volumes:
      - ./measurement_service/app:/app
    command: 
      sh -c "uvicorn main:app --host 0.0.0.0 --reload --port 8000"
    depends_on:
      - postgresql
    env_file:
      - ./measurement_service/.env
    networks:
        - rabbitmq_go_net

  nginx:
    image: nginx:latest
    ports:
      - "8081:8081"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - measurement_service
    networks:
        - rabbitmq_go_net

  postgresql:
    image: postgres
    ports: 
      - 5432:5432
    env_file:
      - ./patient_service/.env
    volumes:
      - /var/cache/postgres_data:/var/lib/postgresql/data
    networks:
        - rabbitmq_go_net
  
  postgresql-test:
    image: postgres
    ports: 
      - 5433:5432
    env_file:
      - ./patient_service/.env
    volumes:
      - /var/cache/postgres_data_test:/var/lib/postgresql/data
  
  postgresql-measurement-svc2:
    image: postgres
    ports: 
      - 5435:5432
    env_file:
      - ./measurement_service/.env
    volumes:
      - /var/cache/postgres_data_measurement_svc:/var/lib/postgresql/data
    networks:
        - rabbitmq_go_net

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./patient_service/.env
    ports: 
      - 5050:80
    depends_on:
      - postgresql
    networks:
        - rabbitmq_go_net
  
  # prometheus:
  #   image: quay.io/prometheus/prometheus:${PROMETHEUS_VERSION}
  #   ports:
  #     - 9090:9090
  #   volumes:
  #     - ./prometheusconfig/prometheus.yml:/var/lib/prometheus/prometheus.yml
  


  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge

  
