version: "3.1"

services:
  app:
    build:
      context: ./patient_service
    ports:
      - 8000:8000
    container_name: painkiller-python-app
    volumes:
      - ./app:/app
    command: sh -c "uvicorn main:app --host 0.0.0.0 --reload"
    depends_on:
      - postgresql
    env_file:
      - ./patient_service/.env

  postgresql:
    image: postgres
    ports: 
      - 5432:5432
    env_file:
      - ./patient_service/.env
    volumes:
      - /var/cache/postgres_data:/var/lib/postgresql/data
  
  postgresql-test:
    image: postgres
    ports: 
      - 5433:5432
    env_file:
      - ./patient_service/.env
    volumes:
      - /var/cache/postgres_data_test:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./patient_service/.env
    ports: 
      - 5050:80
    depends_on:
      - postgresql
