version: "3.7"

services:
  app:
    build:
      context: ./patient_service
    ports:
      - 8001:8000
    container_name: painkiller-python-app
    volumes:
      - ./patient_service/app:/app
    command: sh -c "uvicorn main:app --host 0.0.0.0 --reload --port 8000"
    depends_on:
      - postgresql-measurement-svc2
    env_file:
      - ./patient_service/.env

  measurement_service:
    build:
      context: ./measurement_service
    ports:
      - 8002:8000
    container_name: painkiller-measurement-python-app
    volumes:
      - ./measurement_service/app:/app
    command: sh -c "uvicorn main:app --host 0.0.0.0 --reload --port 8000"
    depends_on:
      - postgresql
    env_file:
      - ./measurement_service/.env

  nginx:
    image: nginx:latest
    ports:
      - "8081:8081"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - measurement_service

  postgresql:
    image: postgres
    ports: 
      - 5432:5432
    env_file:
      - ./patient_service/.env
    volumes:
      - /var/cache/postgres_data:/var/lib/postgresql/data
  
  postgresql-test:
    image: postgres
    ports: 
      - 5433:5432
    env_file:
      - ./patient_service/.env
    volumes:
      - /var/cache/postgres_data_test:/var/lib/postgresql/data
  
  postgresql-measurement-svc2:
    image: postgres
    ports: 
      - 5435:5432
    env_file:
      - ./measurement_service/.env
    volumes:
      - /var/cache/postgres_data_measurement_svc:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./patient_service/.env
    ports: 
      - 5050:80
    depends_on:
      - postgresql

  
