"""add

Revision ID: e12cbd21dd56
Revises: 
Create Date: 2023-08-03 04:39:16.211874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e12cbd21dd56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurements',
    sa.Column('measurement_id', sa.UUID(), nullable=False),
    sa.Column('temperature_celsius', sa.Float(), nullable=False),
    sa.Column('blood_pressure_sys', sa.Integer(), nullable=True),
    sa.Column('blood_pressure_dias', sa.Integer(), nullable=True),
    sa.Column('body_weight', sa.Float(), nullable=False),
    sa.Column('height_cm', sa.Integer(), nullable=False),
    sa.Column('stroke', sa.Boolean(), nullable=True),
    sa.Column('diabetes', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('measurement_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurements')
    # ### end Alembic commands ###
