"""update

Revision ID: d349477c08dd
Revises: b78918286037
Create Date: 2023-08-10 01:45:27.641481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd349477c08dd'
down_revision = 'b78918286037'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('temperature_celsius', sa.Float(), nullable=False))
    op.add_column('measurements', sa.Column('height_cm', sa.Integer(), nullable=False))
    op.drop_constraint('measurements_patient_id_fkey', 'measurements', type_='foreignkey')
    op.drop_column('measurements', 'temperature')
    op.drop_column('measurements', 'BMI')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('BMI', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('measurements', sa.Column('temperature', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('measurements_patient_id_fkey', 'measurements', 'patients', ['patient_id'], ['patient_id'])
    op.drop_column('measurements', 'height_cm')
    op.drop_column('measurements', 'temperature_celsius')
    # ### end Alembic commands ###
